edition = "2021"
unstable_features = true

chain_width = 30
condense_wildcard_suffixes = true
hard_tabs = true
imports_granularity = "Crate"
imports_layout = "Mixed"
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
newline_style = "Auto"
reorder_impl_items = true
reorder_imports = true
normalize_comments = true
single_line_if_else_max_width = 0
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
